import api from "../axios";
import { withCache, invalidateCachePattern } from "../../utils/apiCache";

/**
 * Contracts API Service
 * Handles CRUD operations and status management for contracts
 */

export interface Contract {
    _id: string;
    contractNumber: string;
    clientId:
        | {
              _id: string;
              business?: { name?: string };
              personal?: { fullName?: string };
          }
        | string;
    quotationId?:
        | {
              _id: string;
              quotationNumber?: string;
          }
        | string;
    contractTerms?: string[];
    body?: string; // Full contract paragraph/text
    startDate: string;
    endDate: string;
    contractImage?: string;
    status: "draft" | "active" | "completed" | "cancelled" | "renewed";
    signedDate?: string | null;
    note?: string;
    createdBy?: {
        fullName?: string;
        email?: string;
    };
    deleted?: boolean;
    createdAt?: string;
    updatedAt?: string;
}

export interface ContractListResponse {
    data: Contract[];
    meta: {
        total: number;
        page: number;
        limit: number;
        totalPages: number;
        hasNextPage: boolean;
        hasPrevPage: boolean;
    };
}

export interface ContractQueryParams {
    page?: number;
    limit?: number;
    search?: string;
    sortBy?: string;
    sortOrder?: "asc" | "desc";
    // Filter parameters
    status?: "draft" | "active" | "completed" | "cancelled" | "renewed";
    clientId?: string;
    quotationId?: string;
    contractNumber?: string;
    startDateFrom?: string;
    startDateTo?: string;
    endDateFrom?: string;
    endDateTo?: string;
    signedDateFrom?: string;
    signedDateTo?: string;
    createdAfter?: string;
    createdBefore?: string;
    updatedAfter?: string;
    updatedBefore?: string;
    expired?: boolean;
    active?: boolean;
    upcomingRenewal?: boolean;
}

/**
 * Get all contracts with pagination and filters
 */
export const getContracts = async (params?: ContractQueryParams): Promise<ContractListResponse> => {
    return withCache(
        "/contracts",
        async () => {
            try {
                const response = await api.get("/contracts", { params });
                return response.data;
            } catch (error) {
                throw error;
            }
        },
        params,
    );
};

/**
 * Get a single contract by ID
 */
export const getContractById = async (id: string): Promise<Contract> => {
    return withCache(`/contracts/${id}`, async () => {
        try {
            const response = await api.get(`/contracts/${id}`);
            return response.data.data;
        } catch (error) {
            throw error;
        }
    });
};

/**
 * Create a new contract
 * Contract number is auto-generated by the backend
 */
export const createContract = async (contractData: {
    clientId: string;
    quotationId?: string;
    contractTerms?: string[];
    body?: string;
    startDate: string;
    endDate: string;
    contractImage?: string;
    status?: "draft" | "active" | "completed" | "cancelled" | "renewed";
    signedDate?: string;
    note?: string;
}): Promise<Contract> => {
    const response = await api.post("/contracts", contractData);
    invalidateCachePattern("/contracts");
    return response.data.contract;
};

/**
 * Update a contract
 */
export const updateContract = async (
    id: string,
    contractData: {
        clientId?: string;
        quotationId?: string;
        contractTerms?: string[];
        body?: string;
        startDate?: string;
        endDate?: string;
        contractImage?: string;
        status?: "draft" | "active" | "completed" | "cancelled" | "renewed";
        signedDate?: string;
        note?: string;
    },
): Promise<Contract> => {
    const response = await api.put(`/contracts/${id}`, contractData);
    invalidateCachePattern("/contracts");
    return response.data.data;
};

/**
 * Delete a contract (soft delete)
 */
export const deleteContract = async (id: string): Promise<void> => {
    await api.delete(`/contracts/${id}`);
    invalidateCachePattern("/contracts");
};

/**
 * Sign a contract - marks it as signed and activates it
 * If no signedDate provided, backend uses current date
 */
export const signContract = async (id: string, signedDate?: string): Promise<Contract> => {
    const response = await api.post(`/contracts/${id}/sign`, signedDate ? { signedDate } : {});
    invalidateCachePattern("/contracts");
    return response.data.data;
};

/**
 * Activate a contract manually
 */
export const activateContract = async (id: string): Promise<Contract> => {
    const response = await api.post(`/contracts/${id}/activate`);
    invalidateCachePattern("/contracts");
    return response.data.data;
};

/**
 * Complete a contract - marks status as 'completed'
 */
export const completeContract = async (id: string): Promise<Contract> => {
    const response = await api.post(`/contracts/${id}/complete`);
    invalidateCachePattern("/contracts");
    return response.data.data;
};

/**
 * Cancel a contract with optional reason
 */
export const cancelContract = async (id: string, reason?: string): Promise<Contract> => {
    const response = await api.post(`/contracts/${id}/cancel`, reason ? { reason } : {});
    invalidateCachePattern("/contracts");
    return response.data.data;
};

/**
 * Renew a contract with new dates - changes status to 'renewed'
 */
export const renewContract = async (id: string, newStartDate: string, newEndDate: string): Promise<Contract> => {
    const response = await api.post(`/contracts/${id}/renew`, {
        newStartDate,
        newEndDate,
    });
    invalidateCachePattern("/contracts");
    return response.data.data;
};
